apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-container
          image: lunix007/user-test-deployed:7b57c4567188c5e940092ac644cca6b9a7c9abf5
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            # Add environment variables here if needed
            - name: ENV
              value: "production"
